language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
addons:
  apt:
    packages:
      - pandoc
install:
  - pandoc -f markdown -t rst README.md > README.rst
  - pip install -r requirements.txt
  - python setup.py install
script: py.test
cache: pip
sudo: false
